# Use postgres/example user/password credentials
version: '3'

services:
  # Use postgres/example user/password credentials
  db:
    image: postgres
    container_name: ai_for_pos_database
    restart: always
    ports:
      - 9601:5432
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: superadmin
    volumes:
      - ./api/back_up_database:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: ai_for_pos_adminer
    restart: always
    ports:
      - 9602:8080

  pgadmin:
    image: dpage/pgadmin4
    container_name: ai_for_pos_pgadmin
    restart: always
    ports:
      - 9603:443
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  database_data:
    driver: local
